### ISSUE TITLE
Accordion Style and Click

### ISSUE THREAD

**Issue by mabuonomo** [jmouriz/angular-material-multilevel-menu#1]
Hi, 

I have some problem to intercept the item clicked in accordion mode

```
app.controller('ControllerMenu', ['$menu', function($menu) {
    console.log("menu");
   $menu.select = function(link) {
      console.log('You are going to', link);
   }

}]);
```

The select function is never called. In replace mode also select is never called but I can use a my custom function

```
 $scope.testMenu = function(test) {
                    var element = test.current.items[0];
                    // console.log(element);
                    if(element.link != '') {
                         window.location.href = element.link;
                    }
                }
```
This function works well in replace mode, instead in accordion mode the element is always the first item of the array.

Thank you

**Comment by jmouriz** [comment]
Hi,

Below I show the correct way to capture the click

```
$menu.callback(function(item) {
   console.log('You are going to', item.link);
});
```

I update the code to pass item as callback argument and show usage in demo.

Regards

**Comment by jmouriz** [comment]
Also I fix the README. Thanks!
